channels:
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- _py-xgboost-mutex=2.0
- absl-py=1.4.0
- acres=0.1.0
- adwaita-icon-theme=48.0
- aiofiles=24.1.0
- aiohttp=3.8.6
- aiosignal=1.3.1
- alsa-lib=1.2.14
- annexremote=1.6.6
- annotated-types=0.7.0
- anyio=4.9.0
- anyqt=0.2.1
- appdirs=1.4.4
- archspec=0.2.5
- argon2-cffi-bindings=21.2.0
- argon2-cffi=21.3.0
- argparse=1.4.0
- arrow=1.2.3
- asttokens=2.2.1
- astunparse=1.6.3
- async-lru=2.0.5
- async-timeout=4.0.3
- at-spi2-atk=2.38.0
- at-spi2-core=2.40.3
- atk-1.0=2.38.0
- attr=2.5.1
- attrs=25.3.0
- awscrt=0.16.26
- babel=2.12.1
- backoff=2.2.1
- backports.functools_lru_cache=1.6.5
- backports.tarfile=1.2.0
- backports=1.0
- baycomp=1.0.2
- beautifulsoup4=4.13.4
- bleach-with-css=6.2.0
- bleach=6.0.0
- blosc2=2.0.0
- boltons=24.0.0
- boto3-stubs=1.28.68
- boto3=1.28.68
- botocore-stubs=1.31.68
- botocore=1.31.68
- bottleneck=1.4.2
- brotli-bin=1.1.0
- brotli-python=1.1.0
- brotli=1.1.0
- bz2file=0.98
- bzip2=1.0.8
- c-ares=1.34.5
- ca-certificates=2025.4.26
- cached-property=1.5.2
- cached_property=1.5.2
- cachetools=5.3.1
- cairo=1.18.4
- catboost=1.2.8
- cattrs=24.1.2
- certifi=2025.1.31
- cffi=1.17.1
- chardet=5.2.0
- charset-normalizer=3.4.2
- ci-info=0.3.0
- click=8.1.8
- cloudpickle=2.2.1
- colorama=0.4.6
- comm=0.2.2
- commonmark=0.9.1
- conda-libmamba-solver=25.4.0
- conda-package-handling=2.4.0
- conda-package-streaming=0.11.0
- conda=25.3.1
- contourpy=1.1.0
- copulas=0.9.2
- cpp-expected=1.1.0
- cryptography=41.0.7
- ctgan=0.8.0
- cuda-crt-tools=12.9.41
- cuda-cudart=12.9.37
- cuda-cudart_linux-64=12.9.37
- cuda-cuobjdump=12.9.26
- cuda-cupti=12.9.19
- cuda-nvcc-tools=12.9.41
- cuda-nvdisasm=12.9.19
- cuda-nvrtc=12.9.41
- cuda-nvtx=12.9.19
- cuda-nvvm-tools=12.9.41
- cuda-version=12.9
- cudnn=9.8.0.87
- curl-cffi=0.10.0
- curl=8.13.0
- cycler=0.11.0
- cyrus-sasl=2.1.27
- cython=3.0.0
- datalad=1.1.4
- dbus=1.13.6
- dcm2bids=3.1.1
- dcm2niix=1.0.20230411
- dcmstack=0.9.0
- debugpy=1.6.7.post1
- decorator=5.2.1
- deepdish=0.3.7
- deepecho=0.5.0
- defusedxml=0.7.1
- dictdiffer=0.9.0
- distro=1.9.0
- docutils=0.21.2
- entrypoints=0.4
- epoxy=1.5.10
- et_xmlfile=2.0.0
- etelemetry=0.3.1
- exceptiongroup=1.1.2
- executing=2.2.0
- exifread=3.3.0
- expat=2.7.0
- faker=37.1.0
- fasteners=0.19
- fastjsonschema=2.18.0
- filelock=3.18.0
- flatbuffers=23.5.26
- fmriprep-docker=24.1.1
- fmt=11.1.4
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.15.0
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.42.0
- fqdn=1.5.1
- freetype=2.13.3
- fribidi=1.0.10
- frozendict=2.4.6
- frozenlist=1.4.0
- fsspec=2025.3.2
- future=1.0.0
- gast=0.4.0
- gdk-pixbuf=2.42.12
- genesis-pyapi=1.2.1
- gensim=4.3.2
- gettext-tools=0.24.1
- gettext=0.24.1
- giflib=5.2.2
- git-annex=10.20230626
- git=2.49.0
- glib-tools=2.84.1
- glib=2.84.1
- gmp=6.3.0
- gmpy2=2.1.2
- gnupg=2.5.5
- google-auth-oauthlib=1.0.0
- google-auth=2.22.0
- google-pasta=0.2.0
- gql=3.5.0
- graphite2=1.3.13
- graphql-core=3.2.6
- graphviz=12.2.1
- grpcio=1.56.2
- gst-plugins-base=1.24.11
- gstreamer=1.24.11
- gtk2=2.24.33
- gtk3=3.24.43
- gts=0.7.6
- h11=0.16.0
- h2=4.2.0
- h5py=3.9.0
- harfbuzz=11.1.0
- hdf5=1.14.3
- heudiconv=1.3.2
- hicolor-icon-theme=0.17
- hpack=4.1.0
- html5lib=1.1
- httpcore=1.0.9
- httpx=0.28.1
- humanize=4.12.3
- hyperframe=6.1.0
- icu=75.1
- idna=3.10
- importlib-metadata=8.6.1
- importlib_metadata=8.6.1
- importlib_resources=6.5.2
- ipykernel=6.25.1
- ipython-genutils=0.2.0
- ipython=8.14.0
- ipywidgets=8.1.0
- iso8601=2.1.0
- isodate=0.6.1
- isoduration=20.11.0
- itsdangerous=2.2.0
- jaraco.classes=3.4.0
- jaraco.context=6.0.1
- jaraco.functools=4.1.0
- jedi=0.19.0
- jeepney=0.9.0
- jinja2=3.1.6
- jiter=0.9.0
- jmespath=1.0.1
- joblib=1.5.0
- json5=0.12.0
- jsonpatch=1.33
- jsonpointer=3.0.0
- jsonschema-specifications=2025.4.1
- jsonschema-with-format-nongpl=4.23.0
- jsonschema=4.19.0
- jupyter-client=8.3.0
- jupyter-console=6.6.3
- jupyter-core=5.3.1
- jupyter-events=0.7.0
- jupyter-lsp=2.2.5
- jupyter-server=2.7.0
- jupyter=1.0.0
- jupyter_client=8.6.3
- jupyter_core=5.7.2
- jupyter_events=0.12.0
- jupyter_server=2.15.0
- jupyter_server_terminals=0.5.3
- jupyterlab-server=2.24.0
- jupyterlab-widgets=3.0.8
- jupyterlab=4.0.5
- jupyterlab_pygments=0.3.0
- jupyterlab_server=2.27.3
- jupyterlab_widgets=3.0.15
- keras=2.13.1
- keyring=25.6.0
- keyrings.alt=5.0.2
- keyutils=1.6.1
- kiwisolver=1.4.4
- krb5=1.21.3
- lame=3.100
- lcms2=2.17
- ld_impl_linux-64=2.43
- lerc=4.0.0
- libabseil=20250127.1
- libaec=1.1.3
- libarchive=3.7.7
- libasprintf-devel=0.24.1
- libasprintf=0.24.1
- libassuan=3.0.2
- libblas=3.9.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcap=2.75
- libcblas=3.9.0
- libcbor=0.10.2
- libclang-cpp15=15.0.7
- libclang-cpp20.1=20.1.4
- libclang13=20.1.4
- libclang=16.0.6
- libcublas=12.9.0.13
- libcudss=0.5.0.16
- libcufft=11.4.0.6
- libcufile=1.14.0.30
- libcups=2.3.3
- libcurand=10.3.10.19
- libcurl=8.13.0
- libcusolver=11.7.4.40
- libcusparse=12.5.9.5
- libdeflate=1.23
- libdrm=2.4.124
- libedit=3.1.20250104
- libegl=1.7.0
- libev=4.33
- libevent=2.1.12
- libexpat=2.7.0
- libffi=3.4.6
- libfido2=1.15.0
- libflac=1.4.3
- libfreetype6=2.13.3
- libfreetype=2.13.3
- libgcc-ng=14.2.0
- libgcc=14.2.0
- libgcrypt-devel=1.11.0
- libgcrypt-lib=1.11.0
- libgcrypt-tools=1.11.0
- libgcrypt=1.11.0
- libgd=2.3.3
- libgettextpo-devel=0.24.1
- libgettextpo=0.24.1
- libgfortran-ng=7.5.0
- libgfortran4=7.5.0
- libgfortran5=14.2.0
- libgl=1.7.0
- libglib=2.84.1
- libglvnd=1.7.0
- libglx=1.7.0
- libgomp=14.2.0
- libgpg-error=1.55
- libiconv=1.18
- libjpeg-turbo=3.1.0
- libksba=1.6.7
- liblapack=3.9.0
- libllvm14=14.0.6
- libllvm15=15.0.7
- libllvm19=19.1.7
- libllvm20=20.1.4
- liblzma-devel=5.8.1
- liblzma=5.8.1
- libmagic=5.46
- libmagma=2.9.0
- libmamba=2.1.0
- libmambapy=2.1.0
- libnghttp2=1.64.0
- libnl=3.11.0
- libnsl=2.0.1
- libntlm=1.8
- libnvjitlink=12.9.41
- libogg=1.3.5
- libopenblas=0.3.28
- libopus=1.5.2
- libpciaccess=0.18
- libpng=1.6.47
- libpq=17.4
- libprotobuf=5.29.3
- librsvg=2.58.4
- libsndfile=1.2.2
- libsodium=1.0.20
- libsolv=0.7.32
- libsqlite=3.49.1
- libssh2=1.11.1
- libstdcxx-ng=14.2.0
- libstdcxx=14.2.0
- libsystemd0=257.4
- libtiff=4.7.0
- libtool=2.4.7
- libtorch=2.7.0
- libudev1=257.4
- libuuid=2.38.1
- libuv=1.50.0
- libvorbis=1.3.7
- libwebp-base=1.5.0
- libwebp=1.5.0
- libxcb=1.17.0
- libxcrypt=4.4.36
- libxgboost=3.0.0
- libxkbcommon=1.9.1
- libxml2=2.13.7
- libxslt=1.1.39
- libzlib=1.3.1
- llvm-openmp=20.1.4
- llvmlite=0.41.1
- looseversion=1.3.0
- lsof=4.99.4
- lxml=5.4.0
- lz4-c=1.10.0
- lzo=2.10
- mamba=2.1.0
- markdown-it-py=3.0.0
- markdown=3.4.4
- markupsafe=3.0.2
- matplotlib-base=3.10.1
- matplotlib-inline=0.1.7
- matplotlib=3.8.3
- mdurl=0.1.2
- menuinst=2.2.0
- mistune=3.0.1
- more-itertools=10.7.0
- mpc=1.3.1
- mpfr=4.2.1
- mpg123=1.32.9
- mpmath=1.3.0
- msgpack-python=1.1.0
- msgpack=1.0.5
- multidict=6.0.4
- multitasking=0.0.9
- munkres=1.1.4
- mutagen=1.47.0
- mypy-boto3-s3=1.28.55
- mysql-common=9.0.1
- mysql-libs=9.0.1
- nbclient=0.10.2
- nbconvert-core=7.16.6
- nbconvert=7.7.3
- nbformat=5.10.4
- nccl=2.26.5.1
- ncurses=6.5
- ndf=0.1.4
- nest-asyncio=1.5.7
- networkx=3.4.2
- nibabel=5.3.2
- nipype=1.10.0
- nlohmann_json=3.11.3
- nltools=0.4.7
- nomkl=1.0
- notebook-shim=0.2.4
- notebook=7.0.2
- npth=1.8
- nspr=4.36
- nss=3.111
- ntbtls=0.3.2
- numba=0.58.1
- numexpr=2.8.5
- numpy=1.24.3
- oauthlib=3.2.2
- openai=1.77.0
- openjpeg=2.5.3
- openldap=2.6.9
- openneuro-py=2024.2.0
- openpyxl=3.1.5
- openssh=10.0p1
- openssl=3.5.0
- opentsne=1.0.2
- opt-einsum=3.3.0
- optree=0.15.0
- orange-canvas-core=0.1.35
- orange-widget-base=4.22.0
- orange3-associate=1.3.0
- orange3-bioinformatics=4.8.0
- orange3-educational=0.7.1
- orange3-explain=0.6.6
- orange3-imageanalytics=0.12.1
- orange3-network=1.8.0
- orange3-prototypes=0.19.0
- orange3-timeseries=0.6.0
- orange3=3.36.1
- overrides=7.7.0
- p7zip=16.02
- packaging=23.1
- pandas-datareader=0.10.0
- pandas=2.0.3
- pandocfilters=1.5.0
- pango=1.56.3
- parso=0.8.4
- pathlib=1.0.1
- patool=4.0.0
- patsy=1.0.1
- pcre2=10.44
- peewee=3.18.1
- perl=5.32.1
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=11.1.0
- pip=23.1.2
- pixman=0.46.0
- pkgutil-resolve-name=1.3.10
- platformdirs=3.10.0
- plotly=5.24.1
- pluggy=1.5.0
- ply=3.11
- point-annotator=2.0.0
- popt=1.16
- prometheus-client=0.17.1
- prometheus_client=0.21.1
- prompt-toolkit=3.0.51
- prompt_toolkit=3.0.51
- propcache=0.3.1
- protobuf=4.23.4
- prov=2.0.1
- psutil=7.0.0
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pulseaudio-client=17.0
- pure_eval=0.2.3
- puremagic=1.29
- py-cpuinfo=9.0.0
- py-xgboost=3.0.0
- pyasn1-modules=0.3.0
- pyasn1=0.5.0
- pybind11-abi=4
- pybind11-global=2.13.6
- pybind11=2.13.6
- pyclipper=1.3.0.post5
- pycosat=0.6.6
- pycparser=2.22
- pydantic-core=2.3.0
- pydantic=2.0.3
- pydicom=3.0.1
- pydot=3.0.4
- pygments=2.15.1
- pylibjpeg-libjpeg=2.2.0
- pynv=0.3
- pyopenssl=23.3.0
- pyparsing=3.0.9
- pyperclip=1.9.0
- pyqt5-sip=12.12.2
- pyqt=5.15.9
- pyqtgraph=0.13.7
- pyqtwebengine=5.15.9
- pysocks=1.7.1
- python-dateutil=2.9.0.post0
- python-fastjsonschema=2.21.1
- python-gitlab=5.6.0
- python-graphviz=0.20.3
- python-json-logger=2.0.7
- python-louvain=0.16
- python-tzdata=2025.2
- python=3.10.13
- python_abi=3.10
- pytorch=2.7.0
- pytz=2023.3
- pywin32-on-windows=0.1.0
- pyyaml=6.0.2
- pyzmq=26.4.0
- qasync=0.27.1
- qhull=2020.2
- qt-main=5.15.15
- qt-webengine=5.15.15
- qtconsole-base=5.6.1
- qtconsole=5.4.3
- qtpy=2.3.1
- rdflib=6.3.2
- rdma-core=57.0
- rdt=1.16.0
- readline=8.2
- referencing=0.36.2
- regex=2024.11.6
- reproc-cpp=14.2.5.post0
- reproc=14.2.5.post0
- requests-cache=1.2.1
- requests-ftp=0.3.1
- requests-oauthlib=1.3.1
- requests-toolbelt=1.0.0
- requests=2.32.3
- requests_cache=0.4.13
- resdk=19.0.1
- rfc3339-validator=0.1.4
- rfc3986-validator=0.1.1
- rich=14.0.0
- rpds-py=0.9.2
- rsa=4.9
- rsync=3.4.1
- ruamel.yaml.clib=0.2.8
- ruamel.yaml=0.18.10
- s3transfer=0.7.0
- scikit-learn=1.1.3
- scipy=1.11.1
- sdmetrics=0.13.0
- sdv=1.8.0
- seaborn=0.12.2
- secretstorage=3.3.3
- send2trash=1.8.3
- serverfiles=0.3.1
- setuptools=75.8.2
- sgqlc=16.4
- shap=0.47.2
- shellingham=1.5.4
- simdjson=3.12.3
- simplejson=3.20.1
- single-sample-gsea=0.2.0
- sip=6.7.12
- six=1.17.0
- sklearn=0.0.post7
- sleef=3.8
- slicer=0.0.8
- slumber=0.7.1
- smart-open=6.4.0
- sniffio=1.3.1
- soupsieve=2.4.1
- spdlog=1.15.1
- sqlite=3.49.1
- stack_data=0.6.3
- statsmodels=0.14.4
- sympy=1.14.0
- tables=3.8.0
- tenacity=9.1.2
- tensorboard-data-server=0.7.1
- tensorboard=2.13.0
- tensorflow-estimator=2.13.0
- tensorflow-io-gcs-filesystem=0.33.0
- tensorflow=2.13.0
- termcolor=2.3.0
- terminado=0.18.1
- threadpoolctl=3.6.0
- tiktoken=0.9.0
- tinycss2=1.4.0
- tk=8.6.13
- toml=0.10.2
- tomli=2.2.1
- tornado=6.4.2
- tqdm=4.67.1
- traitlets=5.9.0
- traits=7.0.2
- triton=3.3.0
- truststore=0.10.1
- typer-slim-standard=0.15.3
- typer-slim=0.15.3
- typer=0.15.3
- types-awscrt=0.19.3
- types-python-dateutil=2.9.0.20241206
- types-s3transfer=0.7.0
- typing-extensions=4.5.0
- typing_extensions=4.13.2
- typing_utils=0.1.0
- tzdata=2025b
- tzlocal=5.1
- ujson=5.10.0
- unicodedata2=16.0.0
- uri-template=1.3.0
- url-normalize=2.2.1
- urllib3=1.26.16
- wayland=1.23.1
- wcwidth=0.2.6
- webcolors=24.11.1
- webencodings=0.5.1
- websocket-client=1.6.1
- werkzeug=2.3.6
- wheel=0.45.1
- whoosh=2.7.4
- widgetsnbextension=4.0.8
- wrapt=1.15.0
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.1
- xcb-util-renderutil=0.3.10
- xcb-util-wm=0.4.2
- xcb-util=0.4.1
- xclip=0.13
- xgboost=3.0.0
- xkeyboard-config=2.44
- xlrd=2.0.1
- xlsxwriter=3.2.3
- xorg-compositeproto=0.4.2
- xorg-damageproto=1.2.1
- xorg-fixesproto=5.0
- xorg-inputproto=2.3.2
- xorg-kbproto=1.0.7
- xorg-libice=1.1.2
- xorg-libsm=1.2.6
- xorg-libx11=1.8.12
- xorg-libxau=1.0.12
- xorg-libxcomposite=0.4.6
- xorg-libxcursor=1.2.3
- xorg-libxdamage=1.1.6
- xorg-libxdmcp=1.1.5
- xorg-libxext=1.3.6
- xorg-libxfixes=6.0.1
- xorg-libxi=1.8.2
- xorg-libxinerama=1.1.5
- xorg-libxmu=1.2.1
- xorg-libxrandr=1.5.4
- xorg-libxrender=0.9.12
- xorg-libxshmfence=1.3.3
- xorg-libxt=1.3.1
- xorg-libxtst=1.2.5
- xorg-libxxf86vm=1.1.6
- xorg-randrproto=1.5.0
- xorg-recordproto=1.14.2
- xorg-renderproto=0.11.1
- xorg-util-macros=1.19.3
- xorg-xextproto=7.3.0
- xorg-xf86vidmodeproto=2.3.1
- xorg-xproto=7.0.31
- xsel=1.2.1
- xvfbwrapper=0.2.10
- xxhash=0.8.3
- xz-gpl-tools=5.8.1
- xz-tools=5.8.1
- xz=5.8.1
- yaml-cpp=0.8.0
- yaml=0.2.5
- yarl=1.9.2
- yfinance=0.2.58
- zeromq=4.3.5
- zipp=3.21.0
- zlib=1.3.1
- zstandard=0.23.0
- zstd=1.5.7
name: venv
